services:
  web:
    build: .
    volumes:
      - .:/code

  web_migrate:
    extends:
      service: web
    command: chmod +x ./migration.sh ./migration.sh
  web_run:
    extends:
      service: web
    depends_on:
      - web_migrate
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
