# Generated by Django 3.1.6 on 2021-04-30 10:56

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
