# Generated by Django 3.1.6 on 2021-05-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210501_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_person',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
