# Generated by Django 3.1.6 on 2021-05-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210519_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mohaverh_score',
            new_name='mohavereh_score',
        ),
    ]
