# Generated by Django 3.1.6 on 2021-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210519_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_degree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('مرد', 'م'), ('زن', 'ز')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
