# Generated by Django 3.1.6 on 2021-08-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210607_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_user',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
