# Generated by Django 3.1.6 on 2021-08-12 15:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=accounts.models.upload_to, verbose_name='Image'),
        ),
    ]
