# Generated by Django 3.1.6 on 2021-08-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210812_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name_user',
        ),
    ]
