# Generated by Django 3.1.6 on 2021-08-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
