# Generated by Django 3.1.6 on 2021-08-25 17:27

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('مرد', 'م'), ('زن', 'ز')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True)),
                ('major', models.CharField(blank=True, max_length=30)),
                ('education_degree', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to=accounts.models.upload_to, verbose_name='Image')),
                ('phone', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(blank=True, max_length=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
