# Generated by Django 3.1.6 on 2021-08-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_h'),
    ]

    operations = [
        migrations.DeleteModel(
            name='H',
        ),
    ]
