# Generated by Django 3.1.6 on 2021-08-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_delete_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
