# Generated by Django 3.1.6 on 2021-08-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='H',
        ),
    ]
