# Generated by Django 3.1.6 on 2021-08-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210826_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='H',
        ),
    ]
