# Generated by Django 3.1.6 on 2021-08-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210826_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T',
        ),
    ]
