# Generated by Django 3.1.6 on 2021-08-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_delete_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
