# Generated by Django 3.1.6 on 2021-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadBlog', '0002_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stop_showing',
            field=models.CharField(default='no', max_length=20),
        ),
    ]
