# Generated by Django 3.1.6 on 2021-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadBlog', '0003_post_stop_showing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stop_showing_helper',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='stop_showing',
            field=models.BooleanField(default=False),
        ),
    ]
