# Generated by Django 3.1.6 on 2021-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadBlog', '0004_auto_20210515_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blocked_by_person_for_answering',
            field=models.BooleanField(default=False),
        ),
    ]
