# Generated by Django 3.1.6 on 2021-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadBlog', '0006_auto_20210525_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blocked_by_person_for_validating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='stop_showing_permanently',
            field=models.BooleanField(default=False),
        ),
    ]
