# Generated by Django 3.1.6 on 2021-07-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadBlog', '0008_comment_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
