# Generated by Django 3.1.6 on 2021-09-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadBlog', '0010_auto_20210812_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
