# Generated by Django 3.1.6 on 2021-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadBlog', '0012_auto_20210912_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
