# Generated by Django 3.1.6 on 2021-05-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohavereh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaltext',
            name='has_answer',
            field=models.BooleanField(default=False),
        ),
    ]
