# Generated by Django 3.1.6 on 2021-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohavereh', '0002_informaltext_has_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaltext',
            name='has_answer',
            field=models.CharField(default='no', max_length=20),
        ),
    ]
