# Generated by Django 3.1.6 on 2021-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohavereh', '0003_auto_20210506_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaltext',
            name='validate_answer',
            field=models.CharField(default='no', max_length=20),
        ),
    ]
