# Generated by Django 3.1.6 on 2021-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohavereh', '0004_informaltext_validate_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaltext',
            name='blocked_by_person',
            field=models.BooleanField(default=False),
        ),
    ]
