# Generated by Django 3.1.6 on 2021-05-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohavereh', '0005_informaltext_blocked_by_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informaltext',
            old_name='blocked_by_person',
            new_name='blocked_by_person_for_answering',
        ),
        migrations.AddField(
            model_name='informaltext',
            name='blocked_by_person_for_validating',
            field=models.BooleanField(default=False),
        ),
    ]
