# Generated by Django 3.1.6 on 2021-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohavereh', '0006_auto_20210524_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaltext',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='informaltext',
            name='still_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
